// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: urappi/auth/v1/auth.proto

package authv1

import (
	v1 "github.com/urappi/contracts/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	User                 *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	VerificationRequired bool                   `protobuf:"varint,2,opt,name=verification_required,json=verificationRequired,proto3" json:"verification_required,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResponse) GetVerificationRequired() bool {
	if x != nil {
		return x.VerificationRequired
	}
	return false
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *v1.TokenPair          `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	User          *v1.User               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetTokens() *v1.TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *LoginResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokensRequest) Reset() {
	*x = RefreshTokensRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokensRequest) ProtoMessage() {}

func (x *RefreshTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokensRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokensRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokensRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *v1.TokenPair          `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokensResponse) Reset() {
	*x = RefreshTokensResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokensResponse) ProtoMessage() {}

func (x *RefreshTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokensResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokensResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokensResponse) GetTokens() *v1.TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyEmailRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VerificationToken string                 `protobuf:"bytes,1,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyEmailRequest) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

type VerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User          *v1.User               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailResponse) Reset() {
	*x = VerifyEmailResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailResponse) ProtoMessage() {}

func (x *VerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyEmailResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ForgotPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ForgotPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetToken    string                 `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ResetPasswordRequest) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ResetPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *GetMeResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsValid        bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	UserContext    *v1.UserContext        `protobuf:"bytes,2,opt,name=user_context,json=userContext,proto3" json:"user_context,omitempty"`
	TokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=token_expires_at,json=tokenExpiresAt,proto3" json:"token_expires_at,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urappi_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_urappi_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserContext() *v1.UserContext {
	if x != nil {
		return x.UserContext
	}
	return nil
}

func (x *ValidateTokenResponse) GetTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TokenExpiresAt
	}
	return nil
}

func (x *ValidateTokenResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_urappi_auth_v1_auth_proto protoreflect.FileDescriptor

const file_urappi_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x19urappi/auth/v1/auth.proto\x12\x0eurappi.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1durappi/common/v1/common.proto\"W\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"s\n" +
	"\x10RegisterResponse\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.urappi.common.v1.UserR\x04user\x123\n" +
	"\x15verification_required\x18\x02 \x01(\bR\x14verificationRequired\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"p\n" +
	"\rLoginResponse\x123\n" +
	"\x06tokens\x18\x01 \x01(\v2\x1b.urappi.common.v1.TokenPairR\x06tokens\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x16.urappi.common.v1.UserR\x04user\";\n" +
	"\x14RefreshTokensRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"L\n" +
	"\x15RefreshTokensResponse\x123\n" +
	"\x06tokens\x18\x01 \x01(\v2\x1b.urappi.common.v1.TokenPairR\x06tokens\"W\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x12VerifyEmailRequest\x12-\n" +
	"\x12verification_token\x18\x01 \x01(\tR\x11verificationToken\"[\n" +
	"\x13VerifyEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x16.urappi.common.v1.UserR\x04user\"-\n" +
	"\x15ForgotPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"2\n" +
	"\x16ForgotPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x14ResetPasswordRequest\x12\x1f\n" +
	"\vreset_token\x18\x01 \x01(\tR\n" +
	"resetToken\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"1\n" +
	"\x15ResetPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0e\n" +
	"\fGetMeRequest\";\n" +
	"\rGetMeResponse\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.urappi.common.v1.UserR\x04user\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xd2\x01\n" +
	"\x15ValidateTokenResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12@\n" +
	"\fuser_context\x18\x02 \x01(\v2\x1d.urappi.common.v1.UserContextR\vuserContext\x12D\n" +
	"\x10token_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0etokenExpiresAt\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason2\x84\x06\n" +
	"\vAuthService\x12M\n" +
	"\bRegister\x12\x1f.urappi.auth.v1.RegisterRequest\x1a .urappi.auth.v1.RegisterResponse\x12D\n" +
	"\x05Login\x12\x1c.urappi.auth.v1.LoginRequest\x1a\x1d.urappi.auth.v1.LoginResponse\x12\\\n" +
	"\rRefreshTokens\x12$.urappi.auth.v1.RefreshTokensRequest\x1a%.urappi.auth.v1.RefreshTokensResponse\x12G\n" +
	"\x06Logout\x12\x1d.urappi.auth.v1.LogoutRequest\x1a\x1e.urappi.auth.v1.LogoutResponse\x12V\n" +
	"\vVerifyEmail\x12\".urappi.auth.v1.VerifyEmailRequest\x1a#.urappi.auth.v1.VerifyEmailResponse\x12_\n" +
	"\x0eForgotPassword\x12%.urappi.auth.v1.ForgotPasswordRequest\x1a&.urappi.auth.v1.ForgotPasswordResponse\x12\\\n" +
	"\rResetPassword\x12$.urappi.auth.v1.ResetPasswordRequest\x1a%.urappi.auth.v1.ResetPasswordResponse\x12D\n" +
	"\x05GetMe\x12\x1c.urappi.auth.v1.GetMeRequest\x1a\x1d.urappi.auth.v1.GetMeResponse\x12\\\n" +
	"\rValidateToken\x12$.urappi.auth.v1.ValidateTokenRequest\x1a%.urappi.auth.v1.ValidateTokenResponseB3Z1github.com/urappi/contracts/gen/go/auth/v1;authv1b\x06proto3"

var (
	file_urappi_auth_v1_auth_proto_rawDescOnce sync.Once
	file_urappi_auth_v1_auth_proto_rawDescData []byte
)

func file_urappi_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_urappi_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_urappi_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urappi_auth_v1_auth_proto_rawDesc), len(file_urappi_auth_v1_auth_proto_rawDesc)))
	})
	return file_urappi_auth_v1_auth_proto_rawDescData
}

var file_urappi_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_urappi_auth_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: urappi.auth.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 1: urappi.auth.v1.RegisterResponse
	(*LoginRequest)(nil),           // 2: urappi.auth.v1.LoginRequest
	(*LoginResponse)(nil),          // 3: urappi.auth.v1.LoginResponse
	(*RefreshTokensRequest)(nil),   // 4: urappi.auth.v1.RefreshTokensRequest
	(*RefreshTokensResponse)(nil),  // 5: urappi.auth.v1.RefreshTokensResponse
	(*LogoutRequest)(nil),          // 6: urappi.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),         // 7: urappi.auth.v1.LogoutResponse
	(*VerifyEmailRequest)(nil),     // 8: urappi.auth.v1.VerifyEmailRequest
	(*VerifyEmailResponse)(nil),    // 9: urappi.auth.v1.VerifyEmailResponse
	(*ForgotPasswordRequest)(nil),  // 10: urappi.auth.v1.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil), // 11: urappi.auth.v1.ForgotPasswordResponse
	(*ResetPasswordRequest)(nil),   // 12: urappi.auth.v1.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),  // 13: urappi.auth.v1.ResetPasswordResponse
	(*GetMeRequest)(nil),           // 14: urappi.auth.v1.GetMeRequest
	(*GetMeResponse)(nil),          // 15: urappi.auth.v1.GetMeResponse
	(*ValidateTokenRequest)(nil),   // 16: urappi.auth.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),  // 17: urappi.auth.v1.ValidateTokenResponse
	(*v1.User)(nil),                // 18: urappi.common.v1.User
	(*v1.TokenPair)(nil),           // 19: urappi.common.v1.TokenPair
	(*v1.UserContext)(nil),         // 20: urappi.common.v1.UserContext
	(*timestamppb.Timestamp)(nil),  // 21: google.protobuf.Timestamp
}
var file_urappi_auth_v1_auth_proto_depIdxs = []int32{
	18, // 0: urappi.auth.v1.RegisterResponse.user:type_name -> urappi.common.v1.User
	19, // 1: urappi.auth.v1.LoginResponse.tokens:type_name -> urappi.common.v1.TokenPair
	18, // 2: urappi.auth.v1.LoginResponse.user:type_name -> urappi.common.v1.User
	19, // 3: urappi.auth.v1.RefreshTokensResponse.tokens:type_name -> urappi.common.v1.TokenPair
	18, // 4: urappi.auth.v1.VerifyEmailResponse.user:type_name -> urappi.common.v1.User
	18, // 5: urappi.auth.v1.GetMeResponse.user:type_name -> urappi.common.v1.User
	20, // 6: urappi.auth.v1.ValidateTokenResponse.user_context:type_name -> urappi.common.v1.UserContext
	21, // 7: urappi.auth.v1.ValidateTokenResponse.token_expires_at:type_name -> google.protobuf.Timestamp
	0,  // 8: urappi.auth.v1.AuthService.Register:input_type -> urappi.auth.v1.RegisterRequest
	2,  // 9: urappi.auth.v1.AuthService.Login:input_type -> urappi.auth.v1.LoginRequest
	4,  // 10: urappi.auth.v1.AuthService.RefreshTokens:input_type -> urappi.auth.v1.RefreshTokensRequest
	6,  // 11: urappi.auth.v1.AuthService.Logout:input_type -> urappi.auth.v1.LogoutRequest
	8,  // 12: urappi.auth.v1.AuthService.VerifyEmail:input_type -> urappi.auth.v1.VerifyEmailRequest
	10, // 13: urappi.auth.v1.AuthService.ForgotPassword:input_type -> urappi.auth.v1.ForgotPasswordRequest
	12, // 14: urappi.auth.v1.AuthService.ResetPassword:input_type -> urappi.auth.v1.ResetPasswordRequest
	14, // 15: urappi.auth.v1.AuthService.GetMe:input_type -> urappi.auth.v1.GetMeRequest
	16, // 16: urappi.auth.v1.AuthService.ValidateToken:input_type -> urappi.auth.v1.ValidateTokenRequest
	1,  // 17: urappi.auth.v1.AuthService.Register:output_type -> urappi.auth.v1.RegisterResponse
	3,  // 18: urappi.auth.v1.AuthService.Login:output_type -> urappi.auth.v1.LoginResponse
	5,  // 19: urappi.auth.v1.AuthService.RefreshTokens:output_type -> urappi.auth.v1.RefreshTokensResponse
	7,  // 20: urappi.auth.v1.AuthService.Logout:output_type -> urappi.auth.v1.LogoutResponse
	9,  // 21: urappi.auth.v1.AuthService.VerifyEmail:output_type -> urappi.auth.v1.VerifyEmailResponse
	11, // 22: urappi.auth.v1.AuthService.ForgotPassword:output_type -> urappi.auth.v1.ForgotPasswordResponse
	13, // 23: urappi.auth.v1.AuthService.ResetPassword:output_type -> urappi.auth.v1.ResetPasswordResponse
	15, // 24: urappi.auth.v1.AuthService.GetMe:output_type -> urappi.auth.v1.GetMeResponse
	17, // 25: urappi.auth.v1.AuthService.ValidateToken:output_type -> urappi.auth.v1.ValidateTokenResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_urappi_auth_v1_auth_proto_init() }
func file_urappi_auth_v1_auth_proto_init() {
	if File_urappi_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urappi_auth_v1_auth_proto_rawDesc), len(file_urappi_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urappi_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_urappi_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_urappi_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_urappi_auth_v1_auth_proto = out.File
	file_urappi_auth_v1_auth_proto_goTypes = nil
	file_urappi_auth_v1_auth_proto_depIdxs = nil
}
